### ISSUE TITLE
Configure CUDA and other library versions

### ISSUE THREAD

**Issue by djwessel** [run-ai/genv#11]
Hey, first of all, really cool idea for a tool.

One of the most annoying aspects of sharing a workstation with others is managing different needs for library versions (cuDNN, CUDA Toolkit, etc.). While PyTorch handles this by wrapping the required libraries into the python module, TensorFlow still requires users to install the necessary library versions themselves.

Do you consider supporting the management of the different library/driver versions per environment through this tool?

**Comment by jonathancosme** [comment]
@djwessel you can actually use conda to manage this. 

1. create your conda environments with the appropriate packages and version
2. activate your conda environment
3. **use genv commands within the activate conda environment**

You can watch a live example of how this is done here (starting at 4:38):
https://youtu.be/_WZR_aO73LU

**Comment by djwessel** [comment]
Thanks, so there is a separation of concerns between the different tools.
