### ISSUE TITLE
Incompatible with Anaconda

### ISSUE THREAD

**Issue by eyildiz-ugoe** [run-ai/genv#49]
it does not seem like genv is actually compatible with conda. if you do genv activate then activate your conda environment, your genv reservation just dies. similarly, if you first activate your conda environment, then you install genv, you cannot even use genv activate anymore as it rejects the command. it's kinda messy.

**Comment by pablovela5620** [comment]
facing a similar issue, using the vscode extension + conda doesn't seem to work. Whenever I try to install it via the extension. It pip installs and tries to initialize but gives the following error

```
eval "$(genv shell --init)"
No such command 'shell'
```

**Comment by eyildiz-ugoe** [comment]
my solution was to install miniconda, and then passing this command:

`conda install -c conda-forge genv=0.11.0`

now it works

**Comment by razrotenberg** [comment]
great to hear @pablovela5620 and thanks for the update!
I'm closing this issue, pls feel free to open a new one if you encounter additional challenges
