### ISSUE TITLE
Feature request: support for per-user enforcement

### ISSUE THREAD

**Issue by crichardson332** [run-ai/genv#50]
Hello, I'm in an academic AI lab that uses genv to manage access to our compute resources. The tool has been great so far, but one thing that would be really convenient for our lab is the ability to set different quotas/constraints for different users, e.g. setting a lower `max_devices` for certain students in our lab (we want PhD students to have access to more GPUs than undergrads, for example). Having a simple config file for every user that defines their quotas would suffice.

This kind of feature would be greatly appreciated. Thanks!

**Comment by razrotenberg** [comment]
hi @crichardson332 and thanks for reaching out!
this sounds like a super relevant capability to add to Genv.
I also think that it won't take long to implement.

just to make sure, are you using the command `genv remote enforce` from one of the machines (with admin privileges) and want to enforce the usage of GPUs by students that are using `genv remote activate` commands?

or your setup includes only a single machine and we are talking about `genv enforce` and `genv activate` (w/o `remote`)

**Comment by razrotenberg** [comment]
hey @crichardson332 have you had the chance to test it?

**Comment by anindyamaiti** [comment]
I am using genv in a similar fashion in my lab (without remote). The per user enforcement does work as expected. 

Thanks for this very useful tool!

**Comment by razrotenberg** [comment]
hey @anindyamaiti 

thank you for taking the time and sharing your experience here and I'm happy to hear Genv helps you!
