### ISSUE TITLE
performance testing

### ISSUE THREAD

**Issue by incomingflyingbrick** [run-ai/genv#62]
Hi, I would like to test the performance of the GPU when using genv container toolkit. How much performance degradation can be expected when using containers compare to bear metal?

**Comment by razrotenberg** [comment]
hey @incomingflyingbrick ! thanks for reaching out.
when running containers using the Genv container toolkit, you should expect 0 additional overhead, as it adds management capabilities but does not interfere the critical path of accessing the device(s).

however, generally speaking, when running containers you might see some additional overhead compared to when running bare metal processes.
I guess that there is plenty of information online.

and out of curiosity, can you share the use case that you are using the Genv container toolkit with?

**Comment by incomingflyingbrick** [comment]
Thanks for clearing! @razrotenberg , I want to share part of my GPU memory to other poeple online, because I only use a small amount of GPU memory. It's such a waste for computing power.
