### ISSUE TITLE
Can I use genv to replace k8s-device-plugin for AMD GPUs?

### ISSUE THREAD

**Issue by yx-lamini** [run-ai/genv#66]

**Comment by davidLif** [comment]
Hello @yx-lamini,

No, genv cann't replace the kubernetes device plugin for AMD gpus.

1- At this point, genv supports only Nvidia gpus.
2- A k8s device plugin needs to implement a specific API (https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/#device-plugin-implementation). genv doesn't implement this API
